modLoader = "javafml"
loaderVersion = "${loader_version_range}" 
license = "${mod_license}"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mods]] 
modId = "${mod_id}" 
version = "${mod_version}" 
displayName = "${mod_name}" 
authors = "${mod_authors}" 
description = '''${mod_description}'''

[[dependencies."${mod_id}"]] 
modId = "neoforge" 
type = "required" 
versionRange = "${neo_version_range}" 
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "touhou_little_maid"
type = "required"
versionRange = "[1.3.5,)"
ordering = "AFTER"
side = "BOTH"
